[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rounds_protocol = "F4kSCH4tGiakWt25cGqKqrEjEobafeZVre2PJqcEfspg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
